### ISSUE TITLE
KogitoSupportingService - fails deployment when trustStoreSecret is added.

### ISSUE THREAD

**Issue by 5280major** [apache/incubator-kie-kogito-operator#1473]
### Describe the bug

I have been trying to get the data-index to deploy, however, we also use our own custom truststore so that it can communicate with the mangement console as well as our deployed Kogito service.  When adding our custom truststore as a secret (and following the naming convention of cacerts & keyStorePassword) and then adding the trustStoreSecret in the spec schema the deployment ends up in a CrashLoopBackoff.

### Expected behavior

When adding the trustStoreSecret into a KogitoSupportingService yaml file:`spec.trustStoreSecret` the operator should create the following volume mount paths:
```
volumeMounts:
  - name: custom-truststore
    mountPath: /home/kogito/certs/custom-truststore/cacerts
    subPath: cacerts
  - name: custom-truststore
    mountPath: /home/kogito/certs/custom-truststore/keyStorePassword
    subPath: keyStorePassword
```

### Actual behavior

When adding the trustStoreSecret into a KogitoSupportingService yaml file:`spec.trustStoreSecret` the operator creates a Volume mount paths of:

```
volumeMounts:
  - name: custom-truststore
    mountPath: /home/kogito/certs/custom-truststore/cacerts/cacerts
    subPath: cacerts
  - name: custom-truststore
    mountPath: /home/kogito/certs/custom-truststore/cacerts/keyStorePassword
    subPath: keyStorePassword
```

This results in a CrashLoopBackoff with the following error:
`ERROR ---> A custom truststore was specified ('cacerts'), but wasn't found in the path /home/kogito/certs/custom-truststore. Make sure that the path is mounted and accessible in your container`

### How to Reproduce?

Steps to Reproduce:

1. Create truststore secret in OpenShift that contains a `cacerts` key with binary file and a `keyStorePassword` key with string.
2. Create any SupportService using the Kogito Operator and add the name of the secret generated in step 1 to the spec.trustStoreSecret parameter.

### Output of `uname -a` or `ver`

Linux kogito-data-index-mongodb-869cc4855-tkxv8 4.18.0-305.76.1.el8_4.x86_64 #1 SMP Thu Jan 12 10:05:36 EST 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.19" 2023-04-18 LTS OpenJDK Runtime Environment (Red_Hat-11.0.19.0.7-1.el8_7) (build 11.0.19+7-LTS) OpenJDK 64-Bit Server VM (Red_Hat-11.0.19.0.7-1.el8_7) (build 11.0.19+7-LTS, mixed mode, sharing)

### Kogito Operator version or git rev

7.13.2-2

### Additional information

I have attempted to set the CUSTOM_TRUSTSTORE variable to simply use `cacerts/cacerts `hoping that would fix the issue temporarily, however, the operator overwrites that Env variable and therefore it ignores what I attempt to set.

While I am not using the latest version of the operator, I believe this actually affects any version that is utilizing the trustStoreSecret value in their KogitoSupportingService yaml.  
It appears as though the error is in the truststore_reconclier.go file of the operator, where it concatenates `"/" + trustStoreSecretFileKey` onto the end of the MountPath:

```
secretVolumeReference := &VolumeReference{
  Name:      secret.Name,
  MountPath: trustStoreMountPath + "/" + trustStoreSecretFileKey,
  FileMode:  &framework.ModeForCertificates,
}
```

I have submitted this as a Jira issue as well:
[https://issues.redhat.com/browse/KOGITO-9236](url)
